# Generated by Django 2.1.5 on 2019-07-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190612_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-date'], 'verbose_name': 'Продажа', 'verbose_name_plural': 'Продажи'},
        ),
        migrations.AddField(
            model_name='sale',
            name='refund',
            field=models.BooleanField(default=False, verbose_name='Возврат средств'),
        ),
    ]
