# Generated by Django 2.1.5 on 2019-06-11 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
                ('position', models.IntegerField(verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('bar_code', models.IntegerField(verbose_name='Бар код')),
                ('amount', models.IntegerField(verbose_name='Количество в упаковке')),
                ('category', models.ManyToManyField(blank=True, to='shop.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='RetailPriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата установки цены')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.Product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Розничная цена',
                'verbose_name_plural': 'Розничные цены',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время продажи')),
                ('purchase_type', models.CharField(choices=[('retail', 'Розничная'), ('wholesale', 'Оптовая'), ('custom', 'Кастомная')], max_length=50, verbose_name='Метод продажи')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличный расчет'), ('card', 'Расчет картой')], max_length=50, verbose_name='Метод олаты')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.Product', verbose_name='Продукт')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Sale')),
            ],
            options={
                'verbose_name': 'Список продаж',
                'verbose_name_plural': '',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='WholesalePriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата установки цены')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.Product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Оптовая цена',
                'verbose_name_plural': 'Оптовые цены',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(blank=True, to='shop.Tag', verbose_name='Тег'),
        ),
    ]
