# Generated by Django 2.1.5 on 2019-06-12 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190612_1115'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingList',
            new_name='ShoppingListItem',
        ),
    ]
