# Generated by Django 2.1.5 on 2019-07-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190714_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='refund',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Возврат средств'),
        ),
    ]
